# Generated by Django 6.0.1 on 2026-01-28 19:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('subdomain', models.SlugField(unique=True, verbose_name='Subdomínio/Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa Cliente',
                'verbose_name_plural': 'Empresas Clientes',
            },
        ),
    ]
